server:
  port: 80
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/electronic_approval?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp